[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run db:generate && npm run build"

[deploy]
  startCommand = "sh start.sh"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
